### ISSUE TITLE
line comment toggle not working

### ISSUE THREAD

**Issue by HubertReX** [Textualize/tcss-vscode-extension#4]
When I press Ctrl + /  on a regular CSS file, a particular line is being commented on, but this is not working when using tcss files and this extension. Is it an issue with the plugin or does one just need to change something in local vs code settings?

**Comment by rodrigogiraoserrao** [comment]
Hmm interesting.
VS Code doesn't know what tcss files are and so it doesn't know how to comment them.
What we can do is tell VS Code what “commenting a line” means via the extension.
We'll look into it.

**Comment by willmcgugan** [comment]
Moving this Todo. That could get annoying.

**Comment by HubertReX** [comment]
grate to hear and looking forward to this small enhancement 💪

**Comment by rodrigogiraoserrao** [comment]
This should be fixed in 1.1.0.

**Comment by HubertReX** [comment]
@rodrigogiraoserrao works like a charm! Many thanks 🙌
